title: KDD 2023 Workshop on Data Science and AI for Sports (DSAI4Sports)
description: Long Island, CA, USA. Aug 7, 2023
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
imagesurl: "./images/"
thumbsurl: "./images/"